# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: "tr-TR"
title: Programlama Güncesi
title_separator : "-"
email: esen.yalim@gmail.com
description: C# Python Programming
twitter_username: username
github_username: eykaraduman
minimal_mistakes_skin: default
search: true
date_format: "%d-%m-%Y"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-spaceship
  - jekyll-mermaid

author:
  name   : "Esen Yalım Karaduman"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Programlama ve inşaat mühendisliği uygulamaları ile ilgili bir mühendisim."
  location  : "Ankara"
  email  : "esen.yalim@gmail.com"
  
  links:
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/eykaraduman/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/eykaraduman"

footer:
      
comments:
  provider: "disqus"
  disqus:
    shortname: "esenyalim"
    
collections:
  acad-net-beginner:
    output: true
    permalink: /:collection/:path/
    
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: true
  #   sidebar:
  #     nav: "sidemenu"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
  # _acad-net-beginner
  - scope:
      path: ""
      type: acad-net-beginner
    values:
      layout: single
      author_profile: false
      share: true

category_archive:
  type: liquid
  path: /categories/
  
tag_archive:
  type: liquid
  path: /tags/

mermaid:
  src: 'https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js'